[project]
name = "post-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mathieu Dupont", email = "mathieu.dupont@ensta.fr" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.11.0",
]

[tool.ruff]
select = ["ALL"]
