[project]
name = "post-processing"
version = "0.1.0"
description = "This repository is used to process passive acoustic data particularly marine mammals automatic detections and manual annotations according to OSmOSE project format."
authors = [
    {name = "Mathieu Dupont",email = "mathieu.dupont@ensta.fr"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "osmose @ git+https://github.com/Project-OSmOSE/OSEkit.git",
    "astral (>=3.2,<4.0)",
    "easygui (>=0.98.3,<0.99.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "numpy (>=1.24.2,<2.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "pytz (>=2025.1,<2026.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "seaborn (>=0.12.2,<0.13.0)",
    "soundfile (>=0.12.1,<0.13.0)",
    "tqdm (>=4.67.1,<5.0.0)"
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.0"
black = "^25.1.0"
pytest = "^8.3.5"

[tool.ruff]
select = ["ALL"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
